[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.71.0",
    "httpx>=0.28.1",
    "mcp>=1.19.0",
    "python-dotenv>=1.1.1",
]
